# Generated by Django 5.2.17 on 2026-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.PositiveIntegerField()),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(default='policy_match', max_length=40)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('observations_json', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('score_reasons_json', models.JSONField(default=list)),
                ('severity', models.CharField(default='low', max_length=16)),
                ('explanation', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('cmc_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cmc.cmccalllog')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
