# Generated by Django 5.2.17 on 2026-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('lenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lenses.lens'),
        ),
        migrations.AddField(
            model_name='event',
            name='lens_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lenses.lensrun'),
        ),
        migrations.AddField(
            model_name='event',
            name='lens_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='lenses.lensversion'),
        ),
    ]
