# Generated by Django 5.2.17 on 2026-09-13 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lensrun',
            name='lens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='lenses.lens'),
        ),
        migrations.AddField(
            model_name='lensversion',
            name='lens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lenses.lens'),
        ),
        migrations.AddField(
            model_name='lensrun',
            name='lens_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenses.lensversion'),
        ),
        migrations.AlterUniqueTogether(
            name='lensversion',
            unique_together={('lens', 'version')},
        ),
    ]
