# Generated by Django 5.2.17 on 2026-09-14 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0002_initial'),
        ('lenses', '0004_persistent_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversationitem',
            name='item_type',
            field=models.CharField(choices=[('user_message', 'User'), ('assistant_message', 'Assistant'), ('lens_created', 'Lens created'), ('job_created', 'Job'), ('workflow_created', 'Workflow'), ('routine_created', 'Routine'), ('status_update', 'Status'), ('scan_result', 'Scan result'), ('event_result', 'Event'), ('policy_diff', 'Policy diff'), ('execution_error', 'Error'), ('plan', 'Plan'), ('evidence', 'Evidence'), ('verification', 'Verification'), ('execution_receipt', 'Execution receipt')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lensrun',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('loading_policy', 'Loading policy'), ('fetching_cmc', 'Fetching CMC'), ('evaluating', 'Evaluating'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('investigating', 'Investigating'), ('verifying', 'Verifying'), ('repairing', 'Repairing'), ('complete', 'Complete'), ('error', 'Error')], default='queued', max_length=24),
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_agent', models.CharField(choices=[('chief', 'Chief'), ('market', 'Market'), ('research', 'Research'), ('unavailable', 'Unavailable')], default='chief', max_length=24)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('acting', 'Acting'), ('observing', 'Observing'), ('verifying', 'Verifying'), ('complete', 'Complete'), ('needs_more_evidence', 'Needs more evidence')], default='planned', max_length=32)),
                ('input_artifacts', models.JSONField(blank=True, default=list)),
                ('output_artifacts', models.JSONField(blank=True, default=list)),
                ('next_gate', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='lenses.lens')),
                ('lens_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='lenses.lensrun')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lenses.agenttask')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('sensitivity', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_required', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lenses.lens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('result', 'Result'), ('evidence_pack', 'Evidence pack'), ('report', 'Report'), ('verification', 'Verification'), ('execution_receipt', 'Execution receipt')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='lenses.lens')),
                ('lens_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='lenses.lensrun')),
                ('lens_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenses.lensversion')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='lenses.result')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_items', to='lenses.artifact'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='cmc', max_length=64)),
                ('tool', models.CharField(blank=True, max_length=64)),
                ('fields_used', models.JSONField(blank=True, default=list)),
                ('observation_ids', models.JSONField(blank=True, default=list)),
                ('claim', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('supported', 'Supported'), ('unsupported', 'Unsupported'), ('inconclusive', 'Inconclusive'), ('needs_more_evidence', 'Needs more evidence')], default='supported', max_length=32)),
                ('sanitized_excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='lenses.artifact')),
                ('cmc_call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='cmc.cmccalllog')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='lenses.lens')),
                ('lens_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='lenses.lensrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('category', models.CharField(choices=[('monitor', 'Monitor'), ('investigate', 'Investigate'), ('research', 'Research')], default='monitor', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('needs_attention', 'Needs attention')], default='draft', max_length=24)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_jobs', to='lenses.lensrun')),
                ('last_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='lenses.result')),
                ('lens', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='lenses.lens')),
                ('lens_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenses.lensversion')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenses.routine')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('supported', 'Supported'), ('unsupported', 'Unsupported'), ('inconclusive', 'Inconclusive'), ('needs_more_evidence', 'Needs more evidence')], default='supported', max_length=32)),
                ('checks_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='lenses.artifact')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='lenses.lens')),
                ('lens_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='lenses.lensrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
