# Generated by Django 5.2.17 on 2026-09-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmcCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=160)),
                ('params_redacted', models.JSONField(default=dict)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('credit_count', models.PositiveIntegerField(blank=True, null=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('fields_used', models.JSONField(default=list)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
