# Generated by Django 5.2.17 on 2026-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmc', '0001_initial'),
        ('lenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmccalllog',
            name='lens_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmc_calls', to='lenses.lensrun'),
        ),
    ]
